package com.classy.placelog.configuration

import com.classy.placelog.configuration.properties.GitProperties
import io.swagger.v3.oas.models.Components
import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.info.Contact
import io.swagger.v3.oas.models.info.Info
import io.swagger.v3.oas.models.info.License
import io.swagger.v3.oas.models.security.SecurityScheme
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration

@Configuration
class SwaggerConfig(
    private val gitProperties: GitProperties,
) {
    @Bean
    fun openAPI(): OpenAPI {
        return OpenAPI().components(
            Components().apply {
                addSecuritySchemes(BASIC_AUTH, sessionSecurity())
            },
        ).info(info())
    }

    /**
     * OpenAPI Info
     */
    private fun info(): Info {
        return Info().apply {
            title = "Place Log API 문서"
            description = """<h3>Place Log API</h3>
                |<p>You can See Full Source Code at <a href="${gitProperties.remote.origin.url}">GitHub Repository</a></p>
                |<p>API Document is generated by Swagger</p>
                |<h4>Last Commit Information</h4>
                |<p><strong>Message:</strong> ${gitProperties.commit.message.full}</p>
                |<p><strong>Commit ID:</strong> ${gitProperties.commit.id}</p>
                |<p><strong>Commit Time:</strong> ${gitProperties.commit.time}</p>
                |<p><strong>Committed by:</strong> ${gitProperties.commit.user.name} (${gitProperties.commit.user.email})</p>
            """.trimMargin()
            termsOfService = ""
            contact = Contact().apply {
                name = "Namju Kim"
                email = "cmsong111@naver.com"
            }
            license = License().apply {
                name = "MIT License"
                url = "https://opensource.org/licenses/MIT"
            }
            version = gitProperties.build.version
        }
    }

    private fun sessionSecurity(): SecurityScheme {
        return SecurityScheme().apply {
            type = SecurityScheme.Type.APIKEY
            `in` = SecurityScheme.In.COOKIE
            name = "JSSESSIONID"
        }
    }

    companion object {
        const val BASIC_AUTH = "basicAuth"
    }
}
