insert into article(title, content, author_email, picture_url, create_time, update_time)
values ('만드리곤드레밥', '곤드레밥에는 일반적으로 건조 곤드레나물이 사용되는데, 이 곳은 생 곤드레나물을 사용하여 돌솥밥을 만든다. 된장찌개와 함께 열 가지가 넘는 반찬이 제공되는 돌솥곤드레정식이 인기 있다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191209162810545_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('만호갈미 샤브샤브', '샤브샤브, 수육, 구이 등 다양한 방식으로 갈미조개를 요리하는 갈미조개 전문 식당. 국물이 맛있기로 유명한 이 곳은 갈미샤브샤브와 갈미수육이 대표메뉴이다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191216135832825_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('민물가든', '30년간 운영해온 생선찜전문점으로, 전통방식인 나무통을 사용하여 조리하는 것이 특징이다. 20가지 이상의 재료로 만든 양념을 사용하는 이 곳은 묵은지 붕어조림과 붕어찜이 대표메뉴이다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191217101816206_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('부흥식당', '영도의 유명한 제주 자리돔전문점으로 싱싱한 자리돔과 직접 만든 양념장의 맛이 무척 잘 어울린다. 당일 판매 할 수 있는 한정된 양만 판매하고 있는 이 곳은 제주갈치 요리로도 유명하다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191217113924538_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('가야할매밀면', '유명한 밀면전문점으로, 밀가루에 옥수수 전분을 섞어, 다른 밀면전문점들보다 더 탄력있는 면이 특징이다. 육수는 돼지뼈와 소뼈에 각종 야채와 여러 한약재를 섞어 만들고, 사이드 메뉴인 만두도 인기 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191217201857896_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('국제밀면',
        '부산의 수많은 밀면전문점 중에서도 가장 유명한 식당 중 한 곳으로, 소 사골만을 사용한 육수 등 독창적인 방식의 밀면을 만들고 있다. 보통 기계로 잘려진 편육이 고명으로 올려지는데, 이 곳은 손으로 일일이 얇게 찢은 양지머리 고기가 올려지는 것이 특징이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191217202633906_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('물꽁식당', '59년째 3대를 이어 운영해온 전통 있는 아귀요리전문점으로 신선한 아귀를 사용해 아구찜, 수육, 탕을 만든다. 자극적이지 않은 담백한 맛의 아구찜이 대표메뉴로 오래되었지만 청결한 가게가 인상적이다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191218094154651_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('부산명물횟집', '1946년부터 운영해 온 무척 유명한 횟집으로 여러 유명인사들의 단골집이기도 하다. 광어회 한 접시에 고기뼈를 푹 고아서 만든 진하고 담백한 맑은 국과 여섯 가지 밑반찬이 나오는 회정식이 인기메뉴이다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191218095111181_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('원조한양족발', '35년 간 국내산 돼지 족을 사용하여 족발을 만들고 있는 유명한 족발전문점으로, 하루 2번 매장에서 삶은 신선하고 싱싱한 족발 맛으로 유명하다. 고기를 얇게 썰어 맛과 식감을 살린 족발과 냉채 족발이 대표메뉴',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191218102958937_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('이재모피자', '30여년을 운영 중인 피자전문점으로 부산에서 피자가 대중화된 시기를 생각하면 상당한 전통을 자랑하는 유명한 곳이다. 국내산 임실치즈를 사용한 푸짐한 토핑의 피자가 특징이며, 변함없는 맛을 지키고 있다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191218103511820_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('거대갈비', '최상등급의 고기와 최고의 원재료만을 사용한다는 한우숯불구이전문점으로, 깔끔한 실내와 친절한 점원들이 인상적이다. 최상등급의 한우인만큼 가격도 높은 편이지만, 직원이 고기를 구워주는 등 만족도가 높은 식당이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219093030634_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('금수복국 본점',
        '부산에서 가장 유명한 식당 중 한 곳인 46년 전통의 복어요리전문점으로, 우수한 식재를 현지에서 엄선하여 공수하고, 모든 찬류 및 장류와 김치, 양념 등을 직접 만들어 사용한다. 특히 외국인 관광객들이 많이 찾는 곳으로도 유명하다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819172845727_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('다온',
        '한옥의 전통적인 모티브를 활용한 인테리어가 인상적인 한정식전문점으로, 토속적인 소품 으로 장식된 별실이 마련되어 있어 격식 있는 모임의 장소로도 많이 찾는 곳. 한약재와 제철 음식 재료를 활용해서 만든 한식 요리를 곱게 담아 코스로 내는 한정식이 인기',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219100305084_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('동백섬횟집',
        '해운대 그랜드호텔 인근에 있는 자연산 활어회 전문 횟집으로, 생선회를 주문하면 문어숙 회, 멍게, 전복, 가자미구이, 새우튀김 등의 다양한 밑반찬과 식사 후 매운탕 등의 요리가 함께 제공된다. 대부분의 생선은 시가에 따라서 가격이 변동된다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818125906889_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('르꽁비브', '부산의 유명베이커리인 옵스에서 런칭한 전통 프렌치 레스토랑. 프랑스인들에게 프렌치 퀴진을 가르쳐온 셰프의 전통 현지 요리법으로 사계절 제철 식재료를 사용한 다양한 프렌치코스요리를 선보이고 있다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219101750249_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('문스시', 'TV프로그램을 통해 소개된 유명 쉐프가 운영하는 일식전문점으로, 기대를 충족하는 수준 있는 요리들과 깔끔하고 세련된 인테리어가 특징이다. 쉐프가 추천하는 음식으로 구성되는 오마카세 스시 코스가 특히 유명하다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818130348030_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('예이제', '해운대 해변인근에 위치한 한정식전문점으로, 가족모임이나 손님 대접 등으로 많이 찾는 곳이다. 주인이 직접 고른 제철 식재료와 지인이 운영하는 농장에서 키운 채소를 사용하는이 곳은 먹는 것이 고민스러울 정도로 예쁜 음식이 특징이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818133818412_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('원조석대추어탕', '입구를 들어서면 가득 쌓인 장작과 아궁이에 올려 진 커다란 무쇠솥이 눈에 들어온다.
유명한 추어탕전문점인 이 곳의 추어탕은, 강한 화력으로 오래 끓여 부드럽고 풍부한 맛이 특징으로, 논고동무침과 가오리찜도 인기 있다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219104936271_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('원조할매복국', '‘복국촌’으로 알려진 미포 지역의 대표적인 복요리 전문점으로, 부산 향토 음식점 31곳 중하나이다. 복어를 사용한 맑은 탕인 복지리가 대표메뉴이며, 복어죽과 수육, 복불고기와 복어찜 등의 요리도 맛볼 수 있다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219134018171_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('젠스시', '해운대의 유명 일식전문점으로, 명인 인증서를 받은 오너 쉐프가 운영하며, 주방 분위기가 엄격하고, 위생에 무척 신경을 쓰는 것으로도 유명하다. 열 가지의 초밥과 함께 미소시루, 달걀 찜, 튀김 등으로 구성 된 코스요리가 대표메뉴',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219135236542_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('옛날 오막집', '1958년부터 운영하고 있는 유명한 내장구이전문점으로 오랜 세월 사랑받고 있는 곳이다. 이 곳의 내장구이는 전통만큼이나 각별한 맛을 자랑하는데 함께 제공되는 장아찌와 나물들을 곁들여 먹으면 또 다른 맛을 즐길 수 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219141858821_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('평안도족발', '30년 넘게 한자리에서 운영해온 전통 있는 족발전문점으로, 이 지역 사람들에게 오래 사랑 받아온 곳이다. 오래된 식당답게 족발 특유의 냄새가 없는 깔끔하고 균형 잡힌 족발의 맛이 특징이며, 냉채족발과 마늘족발 등의 메뉴도 인기 있다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219141936064_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('한우숯불양곱창', '해운대 중동역 인근의 양곱창 전문점인 이 곳은 특히 소의 첫 번째 위인 특양 양념구이가 유명하다. 주문과 동시에 특제양념을 발라, 점원이 구워주는 이 곳의 특양 구이는 무척 부드 러우면서도 살짝 탄력 있는 식감이 특징이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819165333332_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('쌍둥이돼지국밥', '식사시간에는 길게 줄을 선 모습을 볼 수 있는 유명한 식당으로, 부산의 수 많은 돼지국밥 전문점 중에서도 손에 꼽히는 식당 중 한 곳이다. 아주 부드러운 돼지고기수육이 유명하다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219143010570_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('이층집 564-9', '심플하고 모던한 인테리어가 인상적인 경양식전문식당으로, 등심 돈가스는 고소한 브로콜리 크림스프와 신선한 생 등심 돼지고기 커틀렛과 계절 샐러드가 함께 나온다. 바삭한 돈가스와 특제소스의 밸런스가 훌륭하다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219153031872_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('초원복국 대연본점',
        '무척 유명한 복어요리전문점인 이곳은 50년 경력의 일식요리사인 아버지와 부산 최초의 특수조리사 복어자격증 소지자인 아들이 2대째 경영하고 있는 곳으로, 언제나 많은 손님들로 북적이는 곳이다. 최상급의 복어요리를 만날 수 있는 곳이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191219160045041_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('석화한정식', '차려지는 음식 하나하나가 먹기 아까울 정도로 섬세하게 담겨져 나온다. 격식있는 모임의 장소로도 유명한 고급한정식전문점으로, 버섯탕수와 전복초가 나오는 고향한정식과 관자숙 회와 갈비찜 장어구이가 나오는 어머니한정식이 대표메뉴.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220513092736141_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('함경면옥', '30년 장인의 솜씨로 만든 냉면의 맛은 비교할만한 대상이 드물다. 부산에서 가장 유명한 냉면전문점 중 한 곳으로, 계절을 가리지 않고 항상 많은 사람들이 찾아오는 것이 이곳의 변하지 않는 맛을 증명하고 있다',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512102852754_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('영변횟집',
        '뼈와 함께 먹는 잘게 썬 세꼬시가 특히 유명한 생선회전문점으로, 도다리, 광어, 우럭, 돌돔, 농어 등 다양한 활어를 철에 따라 즐길 수 있다. 특히 가자미나 광어를 이용한 세꼬시가 인기 메뉴로 회를 주문하면 상을 꽉 채우는 반찬과 해산물 등이 함께 제공된다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818134302422_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('방코', '특이한 외관의 이 건물은 화덕에 구운 피자와 파스타를 만드는 곳이다. 신선한 재료와 새로운 조리법을 사용하여 풍부하고 담백한 맛을 내는 것이 특징이다. 트러플로 향을 낸 피자와 블루치즈를 사용한 피자가 대표메뉴이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818100408773_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('얼크니손칼국수(기장본점)', '간단히 준비된 샤브샤브를 먹은 후 직접 면을 넣고 조리해 먹는 칼국수 가격에 비해 푸짐한 재료들이 특징이다. 먼저 샤브샤브를 먹고 그 국물에 칼국수를 만들어 먹고 나면, 점원이 볶음밥을 만들어 준다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819144753937_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('곤국', '곰탕전문식당인 이 곳은 오래 끓여 부드러운 고기와 맛이 진한 국물이 특징으로, 밥을 말아서 나오지 않고, 갓 지은 솥밥이 따로 제공된다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819150211450_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('다이닝센 부산본점', '패밀리레스토랑 다이닝센은 직접 만드는 소스들을 사용하고, 비교적 저렴한 가격에 비해 높은 수준의 음식들이 제공된다. 행사를 위한 시설과 공간도 잘 준비되어 있다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20200820090928003_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('오륙도 가원', '건축상을 받은 아름다운 외관과 잘 가꾸어진 넓은 잔디정원이 인상적이다. 이 곳은 유명한 한우숯불구이 전문식당으로, 제공되는 음식과 서비스 등 모든 것이 무척 고급스럽다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818151745396_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('한우랑', '한우 숯불구이 전문점으로 모든 메뉴는 국내에서 생산된 질 좋은 재료만 사용해 만들어진다. 한우는 특히 굽는 솜씨에 따라 맛의 차이가 크게 나는데, 이 곳은 숙련된 점원이 고기를 구워준다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818152932317_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('해남식당', '김치요리전문식당인 이 곳은 배추산지로 유명한 해남의 배추를 사용 하여, 오랜 시간 숙성시킨 묵은지를 사용하는 것이 특징이며, 다양한 김치요리를 먹을 수 있다. 해남묵은지에 대한 높은 자부심을 가지고 있다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818153601185_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('금강만두',
        '찾기 힘든 골목에 위치해 미식가들만 찾아가는 숨은 가게였던 이 가게는 현재 사람들의 왕래가 많은 자리의 큰 점포로 옮겨 운영하고 있다. 만두가 맛있기도 하지만, 사실 이 곳은 매우면서도 깔끔한 맛의 육개장이 더욱 유명한 특이한 식당이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818170548384_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('고을산채',
        '2006년부터 운영해온 한식당으로, 모든 반찬들을 주인이 직접 만든다. 점심에는 제철반찬이 함께 제공되는 산채정식 비빔밥을 먹으러 오는 사람이 많으며, 저녁에는 소고기버섯전골과 곱창전골이 인기 있다. 저렴한 가격에 푸짐한 식사를 할 수 있는 곳',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200818175032095_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('석화정', '18년간 운영해 온 굴요리 전문점으로, 재철 생굴, 굴구이, 굴튀김, 굴파전, 굴김치 등 굴을 이용한 다양한 음식들을 즐길 수 있다. 특히, 대표메뉴인 굴국밥은 신선한 자연산 굴을 사용 하여, 깔끔하고 풍부한 맛으로 인기 있다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819094049234_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('북경', '연산동의 중심가골목에 위치한 중식당으로 요리를 전문으로 하여 이 지역 회사원들이 회식장소로도 자주 찾는 곳이다. 모든 메뉴의 수준이 높은 곳이기도 하지만, 특히 짜장면이 맛있기로 유명하다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819172514790_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('연산낙지해물탕',
        '해물탕은 원래 푸짐한 해산물들이 담겨 나오는 음식이지만, 이 곳의 해물탕은 음식을 잘모르는 사람도 싱싱하다는 것을 알 수 있는 해산물들이 뚜껑이 닫히지 않을 정도로 담겨 나온다. 해물탕이 익을 때쯤 살아있는 낙지를 손질해 넣어주는 것이 특징이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819103408604_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('웰빙여행', '부산시청 근처의 칼국수와 만두전문점으로, 매생이 칼국수, 들깨 칼국수 등 조금 특별한 칼국수와 함께 푸짐한 만두전골을 먹을 수 있는 곳이다. 만두는 매일매일 직접만들며, 여름에는 직접 갈아만든 콩칼국수를 판매하기도 한다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819170519954_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('옻바다전복 삼계탕', '연산동 중심가골목에 위치한 삼계탕전문점으로, 대표적인 보양음식인 옻나무삼계탕에 전복을 추가하여 먹을 수 있는 것이 특징이다. 식전주로 옻술이 제공되는 이 곳은 TV프로그램에도 소개 된 유명한 식당이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819105118416_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('참참부자', '연산동 중심가골목에 위치한 일식코스전문점으로, 참치와 자연산회를 맛볼 수 있는 곳이다. 코스요리를 전문으로 하는 곳인 만큼 회는 물론이며, 음식 하나하나가 높은 수준이다.점심한정메뉴를 찾는 손님도 많은 곳',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819105753999_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('팔미초밥', '부산의 대표적인 일식전문점 중 한 곳으로, 상업지역인 이 지역에서도 손님을 대접하기 좋은 곳으로 유명한 식당이다. 30년 경력의 오너쉐프가 운영하고 있으며, 이 곳의 코스요리는 가격에 비해 높은 만족도를 자랑한다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819110257649_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('남촌', '청정지역인 지리산 아래 산청의 흑돼지만 사용하고 있는 믿을 수 있는 돼지구이전문점이다. 사용되는 흑돼지 자체가 일반적인 돼지고기와 식감과 맛의 차이가 많이 나며, 껍데기가 붙어 있는 오겹살 흑돼지 고기를 쓰는 것이 특징이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819154352300_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('북경의자전거', '본격적인 중국풍의 인테리어가 특색있는 이 중식당은 중국인 쉐프들이 요리하고 있는 것으로 유명하다. 사용되는 면은 전통방식인 수타로 만들고, 다양하고 많은 종류의 요리들을 만드는 단골 손님이 많은 가게이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200820091146813_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('식당 3선(덕천점)',
        '숯불구이, 파삼겹구이, 밀면 등을 맛볼 수 있는 식당인 이곳은 나이와 취향에 관계없이 즐길 수있는 대중적인 맛이 특징으로, 넓은 공간을 가지고 있어 가족외식장소로 인기 있다. 메인요리인 숯불구이는 조리되어 제공되어서 먹기 편하다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819154140644_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('함경면옥',
        '22년의 전통을 가지고 있는 함흥냉면 전문점으로, 메뉴에 들어가는 모든 재료들을 직접 만든다. 고구마 전분 특유의 탄력과 쫄깃함을 가진 함흥식 냉면 사리가 특징이며, 진한 육수가 맛있는 물냉면과 숙성된 가오리 회가 올라가는 회비빔면이 인기메뉴이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200820091029413_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('디에이블 송도점',
        '유명한 양식레스토랑인 디에이블의 분점으로, 가게 전체에서 보이는 멋진 바다풍경 속에서 특별한 식사를 할 수 있는 곳이다. 시그니처 메뉴인 피자는 페스츄리 도우를 사용해 촉촉한 것이 특징이며, 특제소스를 사용해 매콤하면서 고소한 파스타도 인기 있다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819132345743_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('몽실종가돼지국밥', '감천문화마을 근처에 있는 돼지국밥전문점으로, 청결한 실내와 친절한 점원들이 인상적이 다. 사골뼈를 24시간 이상 푹 고아 만든 국물이 유명하고, 국밥에 들어가는 고기양과 고기 종류를 선택할 수 있는 것이 특징이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819132813484_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('식당 토성동',
        '의외의 장소에 자리하고 있는 아담하고 예쁜 인테리어의 덮밥전문점으로, 간단한 음식, 깔끔한 맛, 친절한 서비스로 유명한 곳이다. 모든 음식이 인기메뉴이긴 하지만, 손질과 숙성을 거쳐 부드러운 맛의 한입 스테이크 덮밥이 대표메뉴라고 한다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819133843312_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('청죽',
        '입구까지 이어진 근사한 정원이 멋진 일식코스요리전문점으로, 이 지역에서는 상견례 등격조 있는 모임의 장소로 많이 이용하는 곳이다. 비교적 비싼 가격의 식당이지만, 맛과 서비스 모두 충분히 만족스러운 곳이라고 한다. 일본식코스요리가 대표메뉴.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819134238418_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('편의방', '이 곳은 3대째 이어오는 중국만두전문점으로, 삼선만두가 유명한 곳이다. 주문과 동시에 만드는 삼선만두는 각종야채와 새우가 가득 차 육즙이 흘러넘친다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819134644126_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('동원장수촌',
        '도자기 장인이 빚어낸 둥그런 뚝배기에 음식을 담아내는 보양음식전문점으로, 모임 등의 장소로도 인기 있는 곳이기도 하다. 한방녹두백숙이 특히 인기있는 메뉴로 황기 구기자 감초 등의 한약제와 녹두오리를 오래 삶아 보약 같은 국물과 부드러운고기가 특징이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819172146946_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('포항가자미물회', '소박한 느낌의 동네식당으로, 시원한 물회에 국수를 말아먹는 것으로 유명한 물회전문점이다. 갖은 양념에 무쳐진 회와 물회 육수가 따로 제공되며, 여름에는 신선한 토마토에 싸먹고 겨울에는 김에 싸먹는 것으로 유명한 곳이다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819143114772_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('괘법쭈꾸미',
        '2007년 괘법동에서 시작한 이 지역의 대표적인 쭈꾸미요리전문점으로, 직접 만든 비법소스를 사용하여 매우면서도, 자꾸 먹게 되는 맛이 특징이다. 대표메뉴는 웰빙쭈꾸미이며, 단일메뉴로 꾸준한 맛을 유지 하고 있는 것이 오랜 인기의 비결이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20200819161305335_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('삼진어묵', '삼진어묵은 1953년부터 3대 째 가억을 잇고있는 대한민국 대표 어묵 브랜드입니다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210415134915004_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('광명집', '20년이 넘게 대를 이어 운영 중인 아구찜/대구뽈찜 전문점으로 신선하고 품질 좋은 재료들로  찜요리를 만들고 있다. 대구뽈찜은 양파가 가득 올려 진 독특한 조리법이 사용되며,  두 가지 찜 요리가 모두 인기 있다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210903144841845_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('명지첫집', '명지를 상징하는 식재료인 소금과 대파를 활용한 젓갈과 대파김치를 보쌈요리에 곁들였다. 기분이 좋아지는 푸짐한 한상차림의 보쌈정식과 쭈꾸미보쌈이 대표메뉴이다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913092353076_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('드마히니 더블유스퀘어점',
        '부산의 유명 베이커리 옵스(OPS)에서 만든 두 번째 프렌치 레스토랑으로 파리 현지 카페의 자유로운 분위기를 살린 공간이 특징이며, 소박하고 정성 가득한 프랑스 요리들과  스페셜티 등급의 다섯 가지 브루잉 커피도 맛 볼 수 있는 곳이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913095514659_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('명품외식 육면정', '다양한 연회석과 어린이 시설, 넓은 주차장을 가지고 있는 큰 규모의 구이전문식당으로 질 좋은 소고기와 신선한 야채들을 제공하고, 최고등급의 위생수준을 인증 받았다. 단체모임이나 가족외식하기 좋은 곳 이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913100010495_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('호포갈비 문현점', '1층의 정육판매점에서 구입한 고기를 2층의 식당에서 구워먹는 방식의 식당으로, 깔끔한 인테리어와 수준 높은 청결상태를 자랑한다. 판매점에서는 질 좋은 육류를 취급하고 있으며, 다양한 부위의 한우를 직접 고를 수 있다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913101952443_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('평산옥',
        '4대에 걸쳐 운영하고 있는 100년 전통의 돼지수육전문식당으로 돼지수육과 수육 삶은 육수에 말은 국수가 유명하다. 국내산 신선한 고기로 만드는 육수는 맑은 국물 색과 담백하지만 진한 맛을 낸다. 100년을 이어온 자부심에 어울리는 맛이다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913104329974_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('공감식당', '보리를 사료로 키운 돼지를 전문가가 직접 선별, 숙성하여 전문교육을 받은 직원들이 직접 구워주는 구이전문점으로, 삼겹살과 구워먹는 치즈가 이 곳의 인기메뉴이다. 다양한 사이드 메뉴도 준비되어 있다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913110103549_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('다옴 (서면 삼정타워점)', '가볍게 즐길 수 있는 한식메뉴를 선보이는 식당으로 남해안멸치로 만드는 육수와 과일을 첨가하여 만든 숙성양념 등 음식준비에 많은 정성을 들인다. 차돌박이가 토핑 된 비빔국수와 비빔밥이 대표메뉴이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913110833421_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('당감밀면', '지역민들이 추천하는 밀면전문점으로 육수와 면·양념에 이르기까지 모든 재료를 주방장의 독자적인 비법으로 만들어 특징적인 밀면의 맛을 자랑한다. 직접 만드는 손만두도 담백한 맛으로 인기 있다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913111405621_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('더브릭하우스', '번잡한 번화가 사이에 예쁜 벽돌집이 보인다. 이곳은 화덕피자가 맛있기로 유명한 이탈리안 레스토랑으로, 클래식한 공간과 클래식한 음악 그리고 이탈리안 음식과 어울리는 다양한 와인이 준비되어 있다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913111907192_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('버거샵', '직접손질하는 1등급 한우 패티와 매일 아침 구운 브리오슈 번으로 만드는 수제버거전문점으로, 외국인 손님들도 많이 찾는 곳이다. 독특한 인테리어를 즐기며 다양한 소품들도 구입하고 볼 수 있는 가게이다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913112340644_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('소수인', '일식을 모티브로 한 새로운 스타일의 요리를 만들고 있는 일본식주점으로 영업을 시작한지 얼마 되지 않아 항상 사람들이 가득한 곳이 되었다. 개성강한 요리들은 술안주로도 식사로도 잘 어울린다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913112639309_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('양평칼국수', '다대포 해수욕장 인근의 식당으로 20년 경력의 칼국수 장인인 주인이 직접 반죽한 숙성면에 국산 배추로 매일 매일 담는 김치가 매력을 더한다. 여름에만 맛 볼 수 있는 냉칼국수, 냉콩칼국수 등의 한정메뉴들도 무척 인기 있다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913114940489_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('영진돼지국밥', '유명한 돼지국밥 전문점 중 한 곳으로, 항상 많은 사람들이 찾아오는 곳이다. 돼지 특유의 냄새를 제거하여 깔끔하고 담백한 맛을 자랑하며 수육과 두부, 볶음김치가  함께 나오는 수육백반이 무척 인기 있다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913131201409_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('신흥반점', '2대째 운영 중인 신흥반점은 서구에서 55년 동안 화교 가족들이 운영해오고 있는 곳으로, 중국 현지의 식당 같은 분위기의 가게에서 다양한 중국요리를 맛 볼 수 있다. 짬뽕국물과 깐풍기가 이 곳에서 추천하는 인기 메뉴이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913133410983_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('동원 숯불 갈비', '한적한 골목길에 숨겨져 있는 이 돼지갈비전문점은 38년간 숯불돼지갈비 한 메뉴로 이 장소를 지켜온 식당이다. 쉽게 찾기 힘든 위치에 있지만 친근하고 꾸준한 맛으로 많은 단골고객들이 찾아오는 곳', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913141552746_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('도날드 즉석 떡볶이', '지역민들에게 추억의 장소인 이 곳은 35년간 운영해온 유명한 즉석떡볶이 전문점으로 해물육수와 고추장 소스를 사용하여 독특한 맛을 자랑한다. 후식으로 판매하는 뻥크림을 먹기 위해 찾아오는 사람들도 많다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913142012236_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('영도우', '부산항이 한눈에 들어오는 장소에 위치한 피자전문점으로 자체개발한 도우로 만든 테두리가 없는 사각형의 디트로이트식 피자가 대표메뉴이다. 임실치즈를 아낌없이 사용하여 풍부한 치즈의 맛을 즐길 수 있다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913152113856_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('함흥보쌈', '냉면전문점으로 시작하여 50여년을 운영 중인 보쌈전문점으로 싱싱한 고기를 사용하고 부드러운 맛으로 유명하다. 오랜 전통을 자랑하는 냉면도 인기메뉴이며 어떤 메뉴를 주문하든 만족스러운 양이 제공된다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913152733413_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('원산면옥', '60여년의 전통을 가진 냉면전문점으로 3대째 운영하고 있는 무척 유명한 곳이다. 한우와 국내산 생 돼지고기, 생닭을 사용하고 10여 가지 재료가 들어간 육수로 만든 냉면은  변하지 않는 맛을 자랑한다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913153317155_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('개미집신도시점', '부산의 대표적인 낙지요리전문점인 개미집의 분점으로, 본점에 뒤쳐지지 않는 맛을 선보이고 있다. 본점과 같이 낙지볶음, 낙지새우볶음, 낙지곱창볶음 등의 요리들이 모두 인기 있으며, 불고기낙지버섯전골과 곱창전골을 찾는 손님도 많다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20210913153737388_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('오리한상', '청둥오리를 사용한 소금구이와 급속 냉동된 오리를 아주 얇게 슬라이스한 불고기가 모두 인기있는 이곳은, 커다란 창을 활용한 깔끔하고 여유로운 공간과 함께 개별룸도 운영하고 있어 가족외식하기에도 좋은 곳이다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510145207922_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('오,유미당', '카페처럼 예쁜 공간에 돈카츠와 쌀국수라는 이색적인 조합의 메뉴를 가진 곳으로, 처음 보면 조금 당황스러운 모습을 가진 토마호크 돈카츠가 가장 인기 있다고 한다. 쌀국수의 수준도 높아 여러 취향을 다 만족시키는 곳이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510151352637_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('만포밀면', '매장에 들어서면 진한 육수냄새가 맛을 기대하게 하는 이곳은 가야식 밀면을 만들고 있는 곳으로, 95년 가게를 연 이후 매일 그 날 판매할 밀면을 시식하는 것으로 시작한다고 한다. 변하지 않는 맛은 언제나 기쁘다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510161651267_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('맛사랑채', '생선구이가 포함된 12가지의 반찬과 함께 매일 다른 국이 제공되는 이곳의 정식은 집밥 보다 더 집밥 같다는 평을 듣고 있다. 인심 가득한 밥상을 만나기 위해 먼 곳에서 찾아오는 손님들도 많다고 한다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510170244967_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('우정까망촌돼지', '구이전문점인 이곳은, 어린 시절 시골에서 먹던 돼지고기의 맛을 재현하기 위해 청정지역에서 키운 돼지를 공수해온다고 한다. 솥뚜껑에 구워먹는 것이 특징인데 맛도 맛이지만, 구워지는 모습이 정말 참기 힘들다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510173949671_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('유메', '8종의 하이볼, 27종의 청주와 국내산 증류주 등 다양한 술과 그에 어울리는 다양한 안주들이 준비되어 있는 일본식주점이지만, 돈카츠전문점이라 알고 있는 사람들도 있을 만큼 오너쉐프가 직접 손질해 만드는 돈카츠가 유명하다고 한다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510175614552_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('금랑횟집 광안리 본점', '수변공원 회센터에 자리한 횟집으로 메인요리인 회와 함께 제공되는 음식들이 다양하고 수준이 높아 회를 즐기지 않는 사람들도 충분히 즐길 만한 곳이다. 광안대교의 전경이 보이는바다풍경으로 유명한 곳이기도 하다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220510180602206_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('난파센', '좋은 재료를 직접 손질하고 직접 만든 특제 소스를 사용해 인기 높은 튀김덮밥전문점으로 밥과 어울리는 튀김을 만들기 위해 무척 많은 연구를 한다고 한다. 밥 위에 올려진 갈색의 튀김이 특징적이다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511104527053_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('화국반점', '43년 전통의 중식전문점으로 간짜장이 특히 유명한 이 곳은, 전통적인 방식의 요리로 외국인들이 많이 찾는 곳이기도 하다. 신세계와 범죄와의 전쟁 등 영화촬영지로도 유명하다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511105704117_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('로얄경양식&스테이크 광안점',
        '광안리의 바다풍경을 즐기며 식사를 할 수 있는 패밀리레스토랑으로 가격에 비해 높은 수준의 음식과 서비스를 제공하고 있다. 조리하는 모습을 직접 볼 수 있는 오픈주방을 운용하고있으며, 바다를 충분히 즐길 수 있는 실내 환경이 인상적이다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511111431528_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('이정태 본참치', '전국의 참치 매니아들이 찾아오는 유명한 참치전문점으로, 조리명인인 오너쉐프가 운영하고 있는 곳이다. 당일재료는 당일소진하고 있으며, 노인들을 위한 행사를 개최하는 등 지역사회에 기여하고 있는 식당이기도 하다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511111651566_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('무궁화 식당', '할머니집에 놀러온 것 같은 느낌을 주는 이곳은 전골요리로 무척 유명한 식당으로, 직접 만든 커다란 만두를 사용한 만두전골이 특히 인기 있다. 신선한 야채를 사용하는 이곳은 항상 변함없는 맛으로 기억되는 곳이기도 하다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511113221248_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('어가초밥', '부산 최대 수산물시장인 자갈치시장과 인접한 일식전문점으로 빠르게 재료를 공수하여 신선한 음식을 제공하고 있다. 대부분의 좌석이 독립된 룸으로 운영되고 있어 편안하게 식사를 즐길 수 있기도 하다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511113442878_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('배꼽시계', '약선 요리를 추구하여 수술 후 환자들도 자주 찾을 만큼 건강한 음식을 만드는 오리요리전문점으로 계절재료를 사용해 장아찌를 담고 2년 이상 숙성시킨 김치를 사용한다. 오리백숙은 시간이 많이 걸리니 2시간 이상 전 예약이 필수다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511115114884_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('배가왕', '매일 2시간씩 육수를 끓이고, 직접 담은 김치를 준비한다. 기본에 충실한 음식을 만들기 위해 노력한다는 칼국수전문점으로, 당근을 갈아 넣어서 밀가루 냄새가 나지 않는 면이 특징이다. 기본은 언제나 정답이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511115634861_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('삼정횟집', '물회로 유명한 이곳은, 점심시간에 이 지역에 있다면 꼭 찾아야하는 식당 중 한곳이다. 매운탕이 함께 제공되는 이곳의 식사메뉴는 특히 직장인들에게 인기가 많으며, 당일 활어만 사용하여 신선도가 높은 것이 특징이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511115844167_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('변소영 백년밥상', '장류부터 밑반찬까지 모두 직접 장만하고 천연조미료만 사용해 맛을 낸다. 직장인들은 물론이고, 입맛이 까다로운 시장상인들과 외국인들도 자주 찾아 유명해진 한식점으로 청결관리에도 무척 신경을 쓰고 있다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511130041847_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('사랑도 횟집', '매일 좋은 횟감을 선별해서 준비하고, 직접 만든 반찬들로 식탁을 채운다. 음식에 대해 정직하게 운영한다는 이곳은 단골이 많기로 유명한 횟집으로, 가격이 다소 높아 보이지만 음식이 차려지면 오히려 저렴하다는 생각이 들게 한다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511131104127_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('삼송초밥', '부산에서 가장 유명한 일식전문점 중 한 곳으로 65년 이상의 역사를 가지고 있으며, 대를 이어 오는 손님들이 이곳의 변치 않는 맛을 보증하고 있다. 특히 김초밥으로 많이 알려져있기도 한 곳이다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511131839264_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('솔리보',
        '스승에게 전수받아 계승·발전시킨 토마토 소스가 특기라는 젊은 오너쉐프는, 스테이크에 쓰는 고기도 직접 정육하여 8시간 이상의 수비드 과정을 거쳐 만들고 있다. 햇살이 들어오는 단정한 인테리어의 공간이 이름처럼 무척 따듯하게 느껴지는 곳이다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511132220417_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('부산족발', '부평동 돼지족발골목에 위치한 족발전문점으로, TV프로그램으로도 자주 소개되는 유명한 식당이다. 이 지역은 부산의 향토음식인 냉채족발이 탄생한 곳으로도 유명한데, 부산족발도 담백하고 탄력 있는 족발과 냉채족발이 유명하다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511132711170_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('시티바캉스', '한적한 주택가에 자리한 파스타전문점인 이곳은 스타일리시한 공간과 스타일리시한 음식으로 특히 젊은이들 사이에서 인기 높다. 도심 속 이색적인 공간에서의 바캉스를 경험하고 싶다면 이곳을 추천한다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511133129967_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('PHOever Yum(포에버얌)', '현지 풍 인테리어의 매장으로 들어오면 동남아의 어촌마을에 있는 느낌이 드는 이곳은 육수와 소스 양념 등을 모두 직접 만들고 있는 베트남음식전문점. 아늑한 분위기로 연인과 가족들이 많이 찾는 곳이기도 하다',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511133523476_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('물레방아 즉석구이', '미식가들 사이에서 꾸준히 좋은 평가를 받고 있는 45년 전통의 구이전문점으로, 한우 안거미 부위를 안금무라는 별칭으로 판매해 더 유명한 곳이기도 하다. 명점으로 인정받는 곳답게 고기 선별에 무척 신경을 쓴다고 한다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511134126759_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('양귀빈 식당 3호점', '아직은 흔하게 보기 힘든 양고기구이전문점으로 카페를 해도 어울릴만한 인테리어가 인상적이다. 숙련된 점원이 고기를 구워주는 이곳은 일식을 전공한 오너가 많은 공부를 통해 질 좋은 양고기를 장만한다고 한다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511135001245_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('고민끝에여기', '향이 강한 멕시코음식을 한국인의 입맛에 맞게 만들어내는 이곳은 매일 신선한 재료를 새로 준비하고, 새우를 주재료로 한 요리들이 많다. 고민 끝에 가게자리를 정했다는 의미의 이름이 무척 독특하다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511135506636_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('명송초밥', '상업지역인 이 지역에서도 접대나 모임하기 좋은 곳으로 유명한 일식전문점으로, 수준 높은 음식에 어울리는 디테일한 플레이팅이 음식을 더욱 돋보이게 만든다. 2~3시간 숙성한 회를 제공하고 있다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511140134038_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('다께', '범일동의 유명 일식전문점으로 오너쉐프가 직접 주재료를 장만하고 있으며, 미리 연락해 두면 원하는 회나 직접 낚시한 생선을 요리해 주기도 한다. 벽면 가득한 유명인들의 사인이 이곳의 맛을 보장하고 있다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511140420748_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('남포삼계탕', '광복로패션거리 근처에 있는 이곳은 50년 이상 운영해 온 유명한 삼계탕 전문점으로, 대표메뉴인 삼계탕은 뱃속에 찹쌀과 인삼, 밤, 대추를 채워 넣은 닭 한 마리를 육수에 넣고 뚝배기에 끓는 채로 내어준다. 전기구이도 인기 있다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511141051338_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('지에이비148', '연인들이 많이 찾는다는 다이닝펍으로 깔끔한 실내와 야외테라스가 인상적이다. 이곳의 시그니처 메뉴인 스테이크는 250도로 달궈진 돌 위에 올려져 레어부터 웰던까지 모든 굽기의 스테이크를 맛볼 수 있어 인기 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511141322616_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('대수정', '40년 이상 운영하고 있는 한식전문점으로 직접 운영하는 농장에서 공수한 재료로 된장, 간장, 김치 등을 만들고 있으며, 질 좋은 한우를 사용한다. 솥밥과 함께 차려지는 가득한 밥상이 기분 좋은 곳이다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511141556325_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('목장원', '원래 소를 키우는 목장이었던 이 곳은 영도에서 가장 유명한 식당 중 한 곳으로, 식당과 카페 공원이 함께 있는 복합외식공간이다. 음식의 수준도 무척 높지만 이곳에서 보이는 바다풍경은 정말 각별하다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511141757671_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('톤쇼우', '오픈 2시간 전부터 대기 줄이 있을 만큼 유명한 돈까스 전문점으로, 두툼하면서도 무척 부드러운 이곳의 돈까스는 참숯으로 훈연하여 놀라운 맛을 선사한다. 기다리는 손님을 위한 배려로 2층에 휴게공간을 운영하고 있기도 하다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511142349184_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('그라치에', '모던한 인테리어의 이 작고 예쁜 이탈리안 레스토랑은 많은 사람들이 이태리음식을 쉽게 접하길 바라는 마음을 담아 운영하고 있다고 한다. 특히, 이곳의 감자뇨끼는 손님들이 추천하는 메뉴이다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511142715519_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('황해도', '깔끔하고 높은 수준의 음식들과 한국전통주를 함께 즐길 수 있는 한식주점인 이곳은, 비교적 낮은 가격으로 여러 가지를 맛볼 수 있는 주안상이 인기 있으며, 무엇보다 좋은 대접을 받았다는 느낌을 주는 매력적인 곳이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511143741751_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('프라한', '빈티지한 느낌의 가구와 공간을 가득 메운 식물들이 영화 속 장면을 연상시키는 이곳은 샌드위치의 빵과 스튜의 토마토소스 등을 직접 만드는 브런치카페로, 언제나 편안한 분위기를 즐기러 오는 손님들로 가득하다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511145040294_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('동촌황정순수육전골', '자극적이지 않지만 풍부한 맛의 국물요리가 특징인 곳으로, 미리 삶아 기름을 제거한 고기를 두껍게 썰어서 사용해 식감이 좋다. 모든 재료는 국내산을 사용하고 단 두 가지 메뉴만 정성껏 준비하고 있다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511153102499_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('소우닭계', '이름처럼 소와 닭을 사용한 한식요리를 전문으로 하는 곳으로, 오너쉐프의 비법으로 만든 부드러운 갈비찜이 유명하다. 밑반찬까지 직접 장만하고 있는 이곳은 혼자서도 갈비찜을 먹을 수 있는 메뉴가 준비되어 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511154322467_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('양지추어탕', '커다란 가마솥으로 끓인 추어탕에 농가에서 공수한 고춧가루를 사용하고, 직접 담은 김치를 사용하는 안심할 수 있는 식당이다. 저렴한 가격에 비해 놀라운 맛과 푸짐한 양의 음식이 제공되어 단골고객이 많다고 한다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511160051644_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('오스테리아비비',
        '이탈리아 요리학교 출신 쉐프와 나폴리피자 장인협회에서 인정한 피자욜로가 운영하고 있는 이곳은 평일 런치는 화덕피자만, 디너와 주말은 코스만 제공된다. 100% 예약제로 운영하는 레스토랑으로 프라이빗한 공간에서 식사를 즐길 수 있다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511161310859_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('웅복', '부부가 운영하고 있는 복어요리전문점으로 식사에 돌솥밥이 제공되는 것이 특징이다. 직접 담은 김치를 사용하며, 당일 재료는 당일 소진하고 있는 이곳의 코스요리는 가격에 비해 놀라울 정도의 음식들이 제공된다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511162214691_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('초량통닭', '1976년부터 40년이 넘게 운영하고 있는 이곳은, 이 지역에서는 모르는 사람이 드문 유명한 식당이다. 이곳의 육즙 가득한 프라이드치킨은 오랫동안 사랑받아온 메뉴로, 언제나 퇴근 후의 직장인들이 만석을 이루고 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511163126270_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('코카모메 초량점', '초량 이바구길의 도심전망이 좋은 곳에 위치한 튀김덮밥전문점으로, 연령층에 관계없이 만족스런 식사로 인기 높은 식당이다. 모든 재료는 국내산으로 준비하고 당일재료는 당일에 소진하고 있다', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511164125446_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('홍성방', '3대에 걸쳐 50년이 넘게 운영해오고 있는 이곳은, 부산차이나타운에서도 가장 유명한 식당 중 한 곳이다. 오래전부터 영주동 물만두 집으로 불렸을 만큼 물만두가 인기 있으며, 주말에는 지방에서도 찾아오는 단골손님들이 많다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511165119901_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('가두리닭숯불구이', '이곳은 소나 돼지처럼 닭을 6가지 부위로 구분하여 원하는 부위만 주문할 수 있는 독특한 방식의 닭구이전문점으로, 요리경영학과 출신의 오너가 야채와 생닭을 직거래로 공수하여 재료의 신선도가 높다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511172410854_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('먹음직', '온천천 카페거리에 있는 구이전문점인 이곳은, 유통도 함께 하고 있어 언제나 신선한 고기가 준비되어 있다. 직접 숙성한 고기와 함께 모든 음식을 정직하고 정성스럽게 제공하고 있는 곳으로 높은 평가를 받고 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511173540705_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('미미루', '유니크한 레시피로 인기 높은 중식당인 이곳은, 6시간 이상 숙성한 고기로 만든 탕수육과 물을 사용하지 않고 양파즙으로 조리한 짜장면이 특히 인기 있다. 식사류의 음식에는 모두 계란프라이를 올려주는 것이 재미있다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511174445294_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('밀보스79',
        '캐주얼한 분위기의 실내가 먼저 눈에 들어오는 이곳은, 파스타나 피자 등의 메뉴와 함께 술을 즐길 수 있는 다이닝펍으로, 비교적 부담 없는 가격으로 좋은 시간을 보낼 수 있는 곳이다. 직접 만든 면과 소스를 사용한 파스타가 특히 맥주와 어울린다고 한다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220511175416697_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('순이네곱창', '대한민국 조리기능장인 오너쉐프는 밑반찬부터 주재료인 곱창의 손질까지 모두 직접 장만하고 있다. 솔잎을 사용하여 잡냄새를 제거하여 더 부드러운 맛을 가진 이곳의 곱창은명인이 준비한 세가지 소스와 만나 더욱 깊은 맛을 자랑한다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512092026544_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('세연정', '소갈비로 유명한 구이전문 패밀리레스토랑으로 청결한 공간과 높은 수준의 서비스를 자랑하는 이곳은, 직거래하는 향토 식자재와 직접 만든 된장, 유명한 산지에서 공수한 재료들을 사용하여 정성들인 음식을 제공하고 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512093357835_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('조방낙지마당', '조방낙지라는 이름의 식당들은 대부분 보증된 맛을 가지고 있는데, 이곳 역시 보증된 낙지전문점이다. 이 지역에서 오랜 시간을 보내온 식당답게 단골손님도 많고, 다른 낙지전문점에 비해 낮은 가격이 마음을 든든하게 한다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512094717830_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('초록담미역국', '미역국에 사용되는 한우는 비계와 힘줄을 직접 제거하고, 직접 만든 반찬과 양념, 그리고 매일 새로 담근 김치를 준비한다. 이곳은 집밥같은 음식을 준비하는 미역국전문점으로 자극적이지 않은 맛으로 유명하다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512100320359_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('타이빈', '태국 정부로부터 Thai select 최고등급인 signature 인증을 받았다는 태국음식전문점으로, 태국인요리사가 준비하는 정통태국음식이 준비되어 있다. 태국으로 여행 온 기분을 느끼게 해주는 인테리어가 무척 인상적인 곳이다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512101521175_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('경찰서 옆 초밥집', '18년 경력의 오너 쉐프가 모든 재료를 직접 만들고 손질한다. 매일 5시간씩 정성껏 준비한 재료와 알찬 구성 그리고 보증된 솜씨로 만들어 내는 초밥은 당신을 실망시키지 않는다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512104118922_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('동백아가씨1961', '빈티지한 인테리어의 카페 같은 이곳은 놀랍게도 유명한 즉석떡볶이 전문점이다. 유명산지의 고춧가루를 사용하는 등 좋은 재료를 사용하고, 라면부터 돈까스까지 다양한 토핑을 추가할 수 있는 매력적인 곳이다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512105240390_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('로위버거', '100% 통새우로 만든 패티와 수제 와사비 소스로 맛을 낸 통새우버거가 인기메뉴인 이곳은 오리지널 레시피 개발과 독특한 분위기로 인기 높은 수제버거전문점이다. 매일 100개 한정 판매라고 하니 서두르는 것을 추천한다.',
        'test4@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512110929592_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('장어촌', '부산에서 장어구이를 이야기할 때 항상 최고로 거론되는 곳 중 한 곳으로, 주문즉시 장만한 장어와 6시간을 끓여 만든 특제한방소스를 경험해 본다면 누구나 그 사실을 인정할 수밖에 없을 것 같다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512112108020_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('전통음식점 원양', '좋은 재료로 직접담은 김치와 밑반찬, 시골집에서 공수한 장류 및 장아찌들을 사용하여 30년이 넘게 꾸준히 직장인들의 사랑을 받아온 곳으로, 미식가들 사이에서 특히 평이 좋은 곳이라 한다. 연회를 위한 단체석도 마련되어 있다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512113115093_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('항정살구공탄', '주문과 함께 썰어내는 고기는 포를 뜨는 방식으로 썰어 더 좋은 식감을 자랑한다. 된장찌개로도 유명한 이곳은 오직 항정살만 전문적으로 취급하고 있는 구이전문점으로 운이 좋다면 유쾌한 이벤트도 경험할 수 있다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512114353372_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('금용', '1960년부터 운영해온 중국만두전문점으로 찐돼지껍질과 사태, 소꼬리 살로 소를 만드는 산둥식 만두를 만들고 있다. 준비해둔 재료가 언제나 당일 소진이 될 정도로 인기가 높다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512130126929_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('웅천집', '1964년부터 3대째 운영하고 있는 전통 있는 식당으로, 3년 숙성 초장으로 만든 특제소스와 먹는 향어회가 특히 유명하지만, 고민 끝에 결국 장어구이와 매운탕까지 모든 메뉴를 먹게 된다는 무서운 곳이기도 하다.',
        'test1@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512131313725_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('이종임 전복뚝배기', '전복요리를 전문으로 하는 이 곳은 신선하고 부드러운 완도산 활전복을 사용하고, 새로운 음식인 전복한우갈비찜을 개발하여 방송에 소개되기도 했다. 전체적으로 염도가 낮은 건강한 음식을 만든다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512133553898_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('평양집', '24년째 운영 중인 평양식 수제만두집으로 흔치 않은 이북식 음식을 만날 수 있는 곳이다. 새벽마다 직접 만든 만두로 손님을 맞이하고 있으며, 100% 녹두를 이용해 만든 녹두전도 인기메뉴다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512143357001_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('대왕불맛', '이곳은 테이크아웃과 배달을 전문으로 하는 내장요리전문점으로, 국내산 곱창·막창을 직화구이로 조리하여 제공한다. 수제양념으로 곱창 특유의 잡냄새를 제거한 매운 곱창메뉴가 인기 있다고 한다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512145041261_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('올리브장작', '통나무 산장에 들어온 듯한 인테리어가 편안한 분위기를 만들고 있는 이곳은 화덕피자와 파스타로 유명한 이탈리안 레스토랑이다. 변하지 않는 꾸준한 맛으로 단골이 많은곳이다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512154744132_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('전골[그집]', '1년이 넘는 시간을 연구하여 만든 레시피로 만든 전골은 다소 찾기 힘든 골목 안쪽의 가게를 사람들로 북적이게 만들었다. 누구나 좋아할 것 같은 국물요리다.', 'test2@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512155859812_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('하오츠', '근처에 관공서가 많아 점심이면 직장인들이 몰려드는 중식당으로 오너쉐프가 직접 선별한 좋은 재료를 사용한다고 한다. 중식당 치고는 조리시간이 조금 긴 편이나, 그만큼의 맛이 보장되어 있다.', 'test3@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512162629589_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('함양본가어탕국수', '민물생선을 갈아서 만든 어탕국수는 생각보다 찾기 어려운 음식이다. 그래서인지 먼 거리에서 찾아오는 손님도 제법 많다는 이곳의 어탕국수는 많이 맵거나 자극적이지 않고 변함없는 맛으로 유명하다.', 'test4@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512164338161_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('오공떵번', '한국에서 흔하게 맛볼 수 있는 쌀국수는 ‘포’라는 하노이식 쌀국수라면, 이곳은 ‘후띠우’라는 호치민식 쌀국수를 만들고 있다. ‘포’와는 달리 향이 강하지 않아 누구나 쉽게 즐길 수 있는 맛이다.', 'test1@test.com',
        'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512165954952_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('옥미아구찜 하단점', '아구찜전문점이 많은 부산에서도 가장 유명한 식당 중 한 곳인 옥미아구찜의 분점으로, 생아귀를 사용하여 맵지 않고 풍부한 맛의 아구찜을 만들고 있다. 부산향토음식점으로 지정되어 있는 곳이기도 하다.',
        'test2@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512171230301_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('우연횟집', '오픈 전 웨이팅으로 유명한 횟집으로, 주문 즉시 잡은 활어를 사용한다. 두툼한 회를 접시가 넘치도록 담아서 주는데 가격마저 저렴한 편이라, 대학가 상권인 이 지역에서 가장 인기 있는 주점 중 한 곳이라고 한다.',
        'test3@test.com', 'https://www.visitbusan.net/uploadImgs/files/cntnts/20220512175424144_ttiel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
