spring:
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
  sql:
    init:
      mode: always
      encoding: UTF-8

  devtools:
    livereload:
      enabled: true

