spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}

  sql:
    init:
      mode: embedded
      encoding: UTF-8


storage:
  imgbb:
    api-key: ${IMGBB_API_KEY}

data.go.kr:
  key: ${DATA_GO_KR_API_KEY}
